# Generated by Django 5.0.2 on 2025-12-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_etablissement_active_salarie_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_compte', models.CharField(max_length=50)),
                ('solde', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=50)),
                ('is_debiteur', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='banque',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='etat',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='etatsalarie',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='etatsalarie',
            name='salarie',
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('solde', models.FloatField(default=0)),
                ('contact', models.CharField(max_length=50)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='api.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=100)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.compte')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.etudiant')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.typetransaction')),
            ],
        ),
        migrations.DeleteModel(
            name='Banque',
        ),
        migrations.DeleteModel(
            name='Cheque',
        ),
        migrations.DeleteModel(
            name='Etablissement',
        ),
        migrations.DeleteModel(
            name='Etat',
        ),
        migrations.DeleteModel(
            name='EtatSalarie',
        ),
        migrations.DeleteModel(
            name='Salarie',
        ),
    ]
