# Generated by Django 5.0.2 on 2025-12-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_classe_compte_typetransaction_remove_salarie_banque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='monthly_charge',
            field=models.FloatField(default=5000),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
